"""llama.cpp reference oracle for qwen.py.

Loads the GGUF via llama-cpp-python, runs a fixed prompt, and dumps per-token
logits + the chosen top-1 ids to .npy files. Our own qwen.py forward is gated
against these numbers.

Usage:
    uv run python qwen/ref_llama.py
    uv run python qwen/ref_llama.py --prompt "Hello world"
    uv run python qwen/ref_llama.py --n-gen 4 --out qwen/ref_cache
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import numpy as np


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model",
                    default="qwen/Qwen3.6-35B-A3B-UD-Q3_K_XL.gguf")
    ap.add_argument("--prompt", default="The capital of France is")
    ap.add_argument("--n-gen", type=int, default=4,
                    help="how many tokens to generate after the prompt")
    ap.add_argument("--top-k", type=int, default=10,
                    help="how many top logits to dump per step")
    ap.add_argument("--out", default="qwen/ref_cache")
    ap.add_argument("--n-ctx", type=int, default=2048)
    ap.add_argument("--n-threads", type=int, default=0,
                    help="0 = llama.cpp default")
    args = ap.parse_args()

    mp = Path(args.model)
    if not mp.exists():
        print(f"model not found: {mp}", file=sys.stderr)
        return 2

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    from llama_cpp import Llama

    t0 = time.time()
    kwargs = dict(
        model_path=str(mp),
        n_ctx=args.n_ctx,
        n_gpu_layers=0,
        logits_all=True,    # need per-token logits for prefill gating
        vocab_only=False,
        verbose=False,
    )
    if args.n_threads > 0:
        kwargs["n_threads"] = args.n_threads
    llm = Llama(**kwargs)
    t_load = time.time() - t0
    print(f"loaded in {t_load:.1f}s  vocab={llm.n_vocab()}  ctx={llm.n_ctx()}")

    # Tokenize with BOS per llama.cpp default.
    prompt_bytes = args.prompt.encode("utf-8")
    toks = llm.tokenize(prompt_bytes, add_bos=True, special=False)
    print(f"prompt: {args.prompt!r}")
    print(f"prompt_tokens: {toks}")

    # Prefill + step-by-step generate so we can dump logits at every position.
    all_tokens: list[int] = list(toks)
    all_logits: list[np.ndarray] = []
    all_topk: list[list[tuple[int, float]]] = []

    # eval the full prompt first (prefill)
    llm.reset()
    t_pref = time.time()
    llm.eval(all_tokens)
    t_pref = time.time() - t_pref
    # llama.cpp scores: shape [n_ctx_so_far, vocab] when logits_all=True
    scores = np.array(llm.scores, copy=True)
    # Keep only positions 0..len(all_tokens)-1
    scores = scores[: len(all_tokens)]
    print(f"prefill: {len(all_tokens)} toks in {t_pref*1000:.0f} ms  "
          f"scores shape {scores.shape}")
    for i in range(len(all_tokens)):
        row = scores[i]
        all_logits.append(row.astype(np.float32))
        tk = np.argpartition(-row, args.top_k)[: args.top_k]
        tk = tk[np.argsort(-row[tk])]
        all_topk.append([(int(t), float(row[t])) for t in tk])

    # Now generate n_gen more tokens, greedy, capturing each step's logits.
    gen_tokens: list[int] = []
    for step in range(args.n_gen):
        row = all_logits[-1]
        nxt = int(np.argmax(row))
        gen_tokens.append(nxt)
        all_tokens.append(nxt)
        llm.eval([nxt])
        # llama.cpp appended one more row of scores
        last = np.array(llm.scores[len(all_tokens) - 1], copy=True)
        all_logits.append(last.astype(np.float32))
        tk = np.argpartition(-last, args.top_k)[: args.top_k]
        tk = tk[np.argsort(-last[tk])]
        all_topk.append([(int(t), float(last[t])) for t in tk])

    # Detokenize what we generated
    gen_bytes = llm.detokenize(gen_tokens)
    print(f"generated tokens: {gen_tokens}")
    try:
        print(f"generated text:   {gen_bytes.decode('utf-8')!r}")
    except UnicodeDecodeError:
        print(f"generated bytes:  {gen_bytes!r}")

    logits = np.stack(all_logits, axis=0)  # [n_pos, vocab]
    top1 = np.argmax(logits, axis=-1).astype(np.int64)
    np.save(out / "prompt_tokens.npy", np.array(toks, dtype=np.int64))
    np.save(out / "gen_tokens.npy", np.array(gen_tokens, dtype=np.int64))
    np.save(out / "all_tokens.npy", np.array(all_tokens, dtype=np.int64))
    np.save(out / "logits.npy", logits)
    np.save(out / "top1.npy", top1)
    with open(out / "topk.txt", "w") as fh:
        fh.write(f"prompt={args.prompt!r}\n")
        fh.write(f"prompt_tokens={toks}\n")
        fh.write(f"gen_tokens={gen_tokens}\n\n")
        for i, row in enumerate(all_topk):
            marker = "P" if i < len(toks) else "G"
            fh.write(f"{marker} pos={i} tok={all_tokens[i]}: "
                     + ", ".join(f"{t}({l:+.3f})" for t, l in row) + "\n")

    print(f"wrote: {out}/{{prompt_tokens,gen_tokens,all_tokens,"
          f"logits,top1}}.npy  topk.txt")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
